name: Cache Node and NPM Dependencies
description: Cache Node and NPM dependencies to speed up workflow runs, based on the package-lock.json file.

inputs:
  node-version:
    description: 'The Node.js version to use'
    required: false
    default: 20.x
  working-directory:
    description: 'The working directory to cache dependencies from'
    required: false
    default: .
  target-env:
    description: '"dev" or "prod". Controls whether dev dependencies are installed or not'
    required: false
    default: dev

runs:
  using: composite
  steps:
    - name: Setup NodeJS version ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: Cache dependencies
      uses: actions/cache@v3
      id: cache-deps
      with:
        path: ${{ inputs.working-directory }}/node_modules
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-${{ inputs.target-env }}-${{ hashFiles(format('{0}/{1}', inputs.working-directory, 'package-lock.json')) }}
    - name: Install dependencies 
      if: steps.cache-deps.outputs.cache-hit != 'true' 
      run: ${{ inputs.target-env == 'dev' && 'npm ci' || 'npm ci --omit=dev' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
