name: 03 - Workflow Runners
on: push
jobs:
    ubuntu-echo:
        name: Ubuntu Echo
        runs-on: ubuntu-latest
        steps:
            - name: Echo Hello Ubuntu
              run: | 
                echo "Runner OS: ${{ runner.os }}"

    macos-echo:
        name: MacOS Echo
        runs-on: macos-latest
        steps:
            - name: Echo Hello MacOS
              run: | 
                echo "Runner OS: ${{ runner.os }}"

    windows-echo:
        name: Windows Echo
        runs-on: windows-latest
        steps:
            - name: Echo Hello Windows
              shell: bash
              run: | 
                echo "Runner OS: $RUNNER_OS"
