name: 09 - Using Functions

on:
    workflow_dispatch:

jobs:
    echo1: 
        runs-on: ubuntu-latest
        steps:
            - name: Print PR title
              run: echo "PR title is ${{ github.event.pull_request.title }}"
            - name: Print PR lables
              run: |
                cat << EOF
                ${{ toJson(github.event.pull_request.labels) }}
                EOF
            - name: Bug step
              if: ${{ !cancelled() && contains(github.event.pull_request.title, 'fix') }}
              run: echo "This is a bug fix"
            - name: Sleeping for 5 seconds
              run: sleep 5
            - name: Failing step
              run: exit 1
            - name: I will be skipped
              if: ${{ success()}}
              run: echo "I will print if previous steps succeed"
            - name: I will exectue
              if: ${{ failure()}}
              run: echo "I will print if any previous steps fail"
            - name: I will always execute if not cancelled
              if: ${{ !cancelled() }}
              run: echo "I will always print if not cancelled"
            - name: I will always execute if cancelled
              if: ${{ cancelled() }}
              run: echo "I will print if cancelled"
