name: 10 - Controlling the execution flow

on:
    workflow_dispatch:
        inputs:
            pass-unit-tests:
                type: boolean
                description: 'Pass unit tests'
                default: true

jobs:
    lint-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04-using-actions/react-app
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
            - name: Install dependencies
              run: npm ci
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: Execute unit tests
              run: npm run test
    deploy-qa:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to QA
              run: echo "Deploy to QA"
    e2e-test:
        runs-on: ubuntu-latest
        steps:
            - name: Execute end to end tests
              run: echo "Executing end to end tests"
    deploy-prod:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to production
              run: echo "Deploy to production"


