name: 11 - Working with inputs

on:
    workflow_dispatch:
        inputs:
            dry-run:
                type: boolean
                description: 'Skip deployment and only print build output'
                default: false
            target:
                type: environment
                required: true
                description: 'Target environment to deploy to'
            tag:
                type: choice
                options:
                    - v1
                    - v2
                    - v3
                default: v3
                description: 'Version to deploy'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: echo "Building from tag ${{ inputs.tag }}"
    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: ${{ !inputs.dry-run }}
        environment: ${{ inputs.target }}
        steps:
            - name: Deploy
              run: echo "Deploying to ${{ inputs.target }}"