name: 12 - Working with outputs

on:
    workflow_dispatch:
        inputs:
            build-status:
                type: choice
                options:
                    - success
                    - failure
                default: success
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{ steps.build.outputs.status }}
            output1: ${{ steps.build.outputs.output1 }}
        steps:
            - name: Print GITHUB_OUTPUT
              run: |
                echo "$GITHUB_OUTPUT"
                cat "$GITHUB_OUTPUT"
            - name: Build
              id: build
              run: |
                echo "$GITHUB_OUTPUT"
                echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
                echo "output1=value1" >> "$GITHUB_OUTPUT"
                echo "output2=value2" >> "$GITHUB_OUTPUT"
                cat "$GITHUB_OUTPUT"
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              if: ${{ needs.build.outputs.build-status == 'success' }}
              run: echo "Deploying"
            - name: Print outputs
              run: |
                echo "Output 1: ${{ needs.build.outputs.output1}}""