name: 13 - Caching

on:
    workflow_dispatch:
        inputs:
            use-cache:
                description: 'Use cache'
                required: true
                default: 'true'
            node-version:
                description: 'Node version'
                type: choice
                options:
                    - '18.x'
                    - '20.x'
                    - '21.x'
                default: '20.x'
jobs:
    build:
        runs-on: ubuntu-latest
        defaults: 
            run:
                working-directory: 13/react-app
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ inputs.node-version }}
            - name: Cache node modules
              uses: actions/cache@v3
              if: ${{ inputs.use-cache }}
              id: cache
              with:
                  path: 13/react-app/node_modules
                  key: ${{ runner.os }}-node-${{ inputs.node-version }}-${{ hashFiles('13/react-app/package-lock.json') }}
            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci
            - name: Run tests
              run: npm run test
            - name: Build
              run: npm run build
            - name: Deploying to non prod
              run: echo "Deploying to non prod"
