name: 16 - Working with environments
run-name: 16 - Working with environments | env - ${{ inputs.target-env }}
on: 
    workflow_dispatch:
        inputs:
            target-env:
                type: environment
                default: staging

jobs:
    echo-staging:
        runs-on: ubuntu-latest
        environment: staging
        env: 
            MY_ENV_VAR: ${{ vars.MY_ENV_VAR  || 'default value' }}
        steps:
            - name: Echo vars
              run: |
                echo "Env variable: ${{ env.MY_ENV_VAR }}"
    echo-prod:
        runs-on: ubuntu-latest
        environment: prod
        env: 
            MY_ENV_VAR: ${{ vars.MY_ENV_VAR  || 'default value' }}
        steps:
            - name: Echo vars
              run: |
                echo "Env variable: ${{ env.MY_ENV_VAR }}"