name: 17 - Custom actions and composite runs
run-name: 17 - Custom actions and composite runs | env - ${{ github.event.inputs.target-env }}

on: 
    workflow_dispatch:
        inputs:
            target-env:
                description: 'Which environment to taget for dependency installation'
                type: choice
                options: ['dev', 'prod']
                default: 'dev'

env:
    working-directory: 17/react-app

jobs:
    builds:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ env.working-directory }}
        steps:
            - uses: actions/checkout@v4
            - name: Cache dependencies
              uses: ./.github/actions/composite-cache-deps
              with:
                  node-version: 20.x
                  working-directory: ${{ env.working-directory }}
                  target-env: ${{ github.event.inputs.target-env }}
            - name: Run tests
              run: npm run test
            - name: Build
              run: npm run build