name: 18 - 1 - Reusable workflow

on:
    workflow_call:
        inputs: 
            target-directory:
                type: string
                required: true
        outputs:
            build-status: 
                value: ${{ jobs.deploy.outputs.build-status }}
                description: The status of the build
            url:
                value: ${{ jobs.deploy.outputs.url }}
                description: The URL of the deployed artifacts

jobs:
    deploy:
        runs-on: ubuntu-latest
        outputs: 
            build-status: ${{ steps.build.outputs.build-status }}
            url: ${{ steps.deploy.outputs.url }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build
              id: build
              run: |
                echo "Building using directory ${{ inputs.target-directory }} ..."
                echo "build-status=success" >> $GITHUB_OUTPUT
            - name: Deploy
              id: deploy
              run: |
                echo "Deploying build artifacts ..."
                echo "url=https://www.google.com" >> $GITHUB_OUTPUT